# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
  - id: prettier
    types: [json]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.44.0
  hooks:
  # - id: markdownlint
  - id: markdownlint-fix

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/crate-ci/typos
  rev: v1.29.7
  hooks:
  - id: typos

- repo: https://github.com/streetsidesoftware/cspell-cli
  rev: v8.17.2
  hooks:
  - id: cspell
    types: [markdown]

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v9.20.1
  hooks:
  - id: eslint

exclude: src/(css|js)/(mermaid|mdbook).*
