version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
ignoreWords: []
import: []

words:

- -DSPICYZ
- PRIVMSG
- aaccept
- ababab
- acked
- acontent
- adate
- aetag
- alast
- bannier
- barify
- bbannier
- bitfield
- bitfields
- blksize
- blocksize
- btest
- camtbx
- codespace
- csmqzc
- dcjq
- dcmake
- duckduckgo
- flamegraphs
- fname
- hashkey
- hilti
- hlto
- inout
- libpcap
- mdbook
- oack
- packagedir
- pcap
- pktio
- pkts
- posix
- quic
- rbdum
- redef
- rgkg
- samply
- siem
- spicyc
- spicyz
- struct
- structs
- subparsers
- testbase
- themself
- tshark
- wireshark
- zeek
- zeekygen
