version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
ignoreWords: []
import: []

words:
- ABABAB
- Bannier
- Blocksize
- CAMTBX
- Codespace
- Csmqzc
- DCJQ
- DCMAKE
- HILTI
- OACK
- PCAP
- POSIX
- QUIC
- SIEM
- Wireshark
- Zeek
- acked
- barify
- bbannier
- bitfield
- bitfields
- blksize
- btest
- duckduckgo
- fname
- hashkey
- hlto
- inout
- libpcap
- mdbook
- packagedir
- pktio
- pkts
- rbdum
- rgkg
- spicyc
- struct
- structs
- subparsers
- tshark
- zeekygen
