#!/usr/bin/env python3

import json
import sys

REPLACEMENT_LANG_SPICY = "ruby"
REPLACEMENT_LANG_ZEEK = "ruby"


def set_lang_spicy(data):
    if isinstance(data, list):
        for x in data:
            set_lang_spicy(x)

    elif isinstance(data, dict):
        for k, v in data.items():
            if k == "content":
                data[k] = v.replace(
                    "```spicy\n", f"```{REPLACEMENT_LANG_SPICY}\n"
                ).replace("```zeek\n", f"```{REPLACEMENT_LANG_ZEEK}\n")
            elif isinstance(data, dict):
                set_lang_spicy(v)


if len(sys.argv) > 1:
    if sys.argv[1] == "supports":
        # sys.argv[2] is the renderer name
        sys.exit(0)

context, book = json.load(sys.stdin)

set_lang_spicy(book)

json.dump(book, sys.stdout)
